completed string-manipulation-2
PhilChoe/m1-0724-code-solutions pull request #19
Opened 2024-07-26 03:20 UTC by PhilChoe

![image](https://github.com/user-attachments/assets/f503eea7-2c44-4c54-807d-b4726721d94c)
![image](https://github.com/user-attachments/assets/8be10785-9e58-47d9-b62e-618babf1b8af)

2024-07-27 20:47 UTC, hesam commented on string-manipulation-2/src/swap-chars.ts
> +function swapChars(
You're using advanced syntax we haven't covered. There's a simpler solution: a simple for loop to go over each index of input, and using if/else conditionals to check we're looking at an index which needs to be swapped.

2024-07-27 20:48 UTC, hesam approved these changes
Please see the comment in code and try to see if you can work the simpler solution.

2024-07-27 21:11 UTC, PhilChoe commented
> Please see the comment in code and try to see if you can work the simpler solution.

thank you for the hint (:

2024-07-30 16:57 UTC, hesam requested changes
For swapChars your new solution is almost correct, but you're missing the case if for loop index i is neither firstIndex nor secondIndex... So at the end of conditional you need an else branch such as these: 


else {
result += string[i]
}

2024-07-31 01:28 UTC, merged

2024-07-31 01:30 UTC, hesam reviewed
yep 👍 💯